import json
import os
from dotenv import load_dotenv
from langchain_cloudflare.chat_models import ChatCloudflareWorkersAI
from langchain_cloudflare.embeddings import CloudflareWorkersAIEmbeddings
from langchain_cloudflare.vectorstores import CloudflareVectorize
from langchain_core.documents import Document
from tqdm import tqdm
import requests

load_dotenv()

ACCOUNT_ID = os.getenv("CF_ACCOUNT_ID")
API_TOKEN = os.getenv("CF_VECTORIZE_API_TOKEN")

# MAKE A API Request, for now using dummy JSON to embedd and vectorize
# TODO - check other e-commerce repos for how they embedd products
with open("demo_products_1.json", "r") as f:
    products = json.load(f)

MODEL_WORKERSAI = "@cf/baai/bge-large-en-v1.5"
embedder = CloudflareWorkersAIEmbeddings(model_name=MODEL_WORKERSAI)
cfVect = CloudflareVectorize(embedding=embedder)

# STEP 2 - Embed the products and create the documents
# Do not specify the id in the metadata, it will be generated by the vectorize index

def build_page_content(p: dict) -> str:
    """Build page_content string from product data"""
    parts = []
    
    # Product name and description
    if p.get("name"):
        parts.append(p["name"])
    if p.get("description"):
        parts.append(p["description"])
    
    # Effects (handle None case)
    effects = p.get("effects")
    if effects:
        if isinstance(effects, list):
            effects_str = ", ".join(str(e) for e in effects if e)
            if effects_str:
                parts.append(f"Effects: {effects_str}")
        else:
            parts.append(f"Effects: {effects}")
    
    # Flavor (handle None case)
    flavor = p.get("flavor")
    if flavor:
        if isinstance(flavor, list):
            flavor_str = ", ".join(str(f) for f in flavor if f)
            if flavor_str:
                parts.append(f"Flavor: {flavor_str}")
        else:
            parts.append(f"Flavor: {flavor}")
    
    # Brand tagline
    if p.get("brand_tagline"):
        parts.append(f"Brand: {p['brand_tagline']}")
    
    # Brand description
    if p.get("brand_description"):
        parts.append(p["brand_description"])
    
    # Subcategory
    if p.get("subcategory"):
        parts.append(f"Subcategory: {p['subcategory']}")
    
    return ". ".join(parts)

def build_metadata(p: dict) -> dict:
    """Build metadata dictionary from product data"""
    metadata = {
        "name": p.get("name", ""),
        "category": p.get("category", ""),
        "type": p.get("type", ""),
        "brand": p.get("brand", ""),
    }
    
    # Subcategory
    if p.get("subcategory"):
        metadata["subcategory"] = p["subcategory"]
    
    # Brand fields
    if p.get("brand_tagline"):
        metadata["brand_tagline"] = p["brand_tagline"]
    if p.get("brand_description"):
        metadata["brand_description"] = p["brand_description"]
    
    # Effects (handle None case)
    effects = p.get("effects")
    if effects:
        if isinstance(effects, list):
            metadata["effects"] = ", ".join(str(e) for e in effects if e)
        else:
            metadata["effects"] = str(effects)
    else:
        metadata["effects"] = ""
    
    # Flavor (handle None case)
    flavor = p.get("flavor")
    if flavor:
        if isinstance(flavor, list):
            metadata["flavor"] = ", ".join(str(f) for f in flavor if f)
        else:
            metadata["flavor"] = str(flavor)
    else:
        metadata["flavor"] = ""
    
    # Weight fields
    if p.get("total_weight_ounce") is not None:
        metadata["total_weight_ounce"] = p["total_weight_ounce"]
    if p.get("total_weight_grams") is not None:
        metadata["total_weight_grams"] = p["total_weight_grams"]
    if p.get("individual_weight_grams") is not None:
        metadata["individual_weight_grams"] = p["individual_weight_grams"]
    
    # THC fields
    if p.get("thc_percentage") is not None:
        metadata["thc_percentage"] = p["thc_percentage"]
    if p.get("thc_total_mg") is not None:
        metadata["thc_total_mg"] = p["thc_total_mg"]
    if p.get("thc_per_unit_mg") is not None:
        metadata["thc_per_unit_mg"] = p["thc_per_unit_mg"]
    if p.get("thc_per_serving_mg") is not None:
        metadata["thc_per_serving_mg"] = p["thc_per_serving_mg"]
    
    # CBD fields
    if p.get("cbd_percentage") is not None:
        metadata["cbd_percentage"] = p["cbd_percentage"]
    if p.get("cbd_total_mg") is not None:
        metadata["cbd_total_mg"] = p["cbd_total_mg"]
    
    # CBG fields (for tinctures)
    if p.get("cbg_total_mg") is not None:
        metadata["cbg_total_mg"] = p["cbg_total_mg"]
    if p.get("cbg_per_serving_mg") is not None:
        metadata["cbg_per_serving_mg"] = p["cbg_per_serving_mg"]
    
    # Volume fields (for tinctures)
    if p.get("total_volume_ml") is not None:
        metadata["total_volume_ml"] = p["total_volume_ml"]
    if p.get("serving_size_ml") is not None:
        metadata["serving_size_ml"] = p["serving_size_ml"]
    
    # Preroll fields
    if p.get("pack_count") is not None:
        metadata["pack_count"] = p["pack_count"]
    
    # Serving size (for concentrates)
    if p.get("serving_size_mg") is not None:
        metadata["serving_size_mg"] = p["serving_size_mg"]
    
    # Inventory status
    if p.get("inStock") is not None:
        metadata["inStock"] = p["inStock"]
    
    # Price
    if p.get("price") is not None:
        metadata["price"] = p["price"]
    
    return metadata

documents = [
    Document(
        page_content=build_page_content(p),
        metadata=build_metadata(p),
    )
    for p in products
]

# Use product IDs as unique vector IDs
ids = [p["id"] for p in products]

# print("Examples for embeddings")
# print("ids", ids)
# print("---------------------------------")
# print("documents", documents[15])


# STEP 1 - Create the Vector DB Table
# vectorize_index_name = "products-demo-1"
# vectorize_index_name = "test-langchain-cloudflare"
vectorize_index_name = "products-demo-2"

# ONLY RUN ONCE INITIALLY to create the Vector DB Table
# cfVect.create_index(index_name=vectorize_index_name, wait=True)

# STEP 3 - Add the documents to the Vector DB Table
# r = cfVect.add_documents(index_name=vectorize_index_name, documents=documents, ids=ids)

# Delete the specific index
# requests.delete(
#     f"https://api.cloudflare.com/client/v4/accounts/{ACCOUNT_ID}/vectorize/v2/indexes/{vectorize_index_name}",
#     headers={
#         "Authorization": f"Bearer {API_TOKEN}",  # ← THIS IS THE KEY LINE
#         "Content-Type": "application/json",
#     },
# )

# Fetch all indeces, Vector DB table info
# response = requests.get(
#     f"https://api.cloudflare.com/client/v4/accounts/{ACCOUNT_ID}/vectorize/v2/indexes",
#     headers={
#         "Authorization": f"Bearer {API_TOKEN}",  # ← THIS IS THE KEY LINE
#         "Content-Type": "application/json",
#     },
# )

# Fetch the specific index, Vector DB table info
# response = requests.get(
#     f"https://api.cloudflare.com/client/v4/accounts/{ACCOUNT_ID}/vectorize/v2/indexes/{vectorize_index_name}/info",
#     headers={
#         "Authorization": f"Bearer {API_TOKEN}",  # ← THIS IS THE KEY LINE
#         "Content-Type": "application/json",
#     },
# )

# curl "https://api.cloudflare.com/client/v4/accounts/a1d51caa9dfb04600e8aefd32367408e/vectorize/v2/indexes" \
# -H "Authorization: Bearer 2L8iOfQM7ugSPVBgz3cP0JgxFTyhYch5-1I46q6g"

if response.status_code != 200:
    raise ValueError(f"Token invalid—status {response.status_code}: {response.text}")

print("response", response.json())
