name = "wine-chat-backend"
main = "src/index.ts"
compatibility_date = "2025-11-24"

[dev]
port = 9174

[vars]
PROFILE_TYPE = "MERCHANT"

[[d1_databases]]
binding = "WINE_DB"
database_name = "wine-catalog"
database_id = "c1d9a63c-d943-46d8-857a-907e0c95a66f"
