-- ============================================
-- WINE CATALOG SEED DATA (real winery + merchant coverage)
-- ============================================
-- Brand rows: ONEHOPE Wine official catalog
-- Merchant rows: curated cross-brand inventory with sparkling-style coverage

-- ============================================
-- ONEHOPE WINE (Brand Concierge)
-- ============================================

INSERT OR REPLACE INTO wines (
  id, name, brand, wine_type, varietal, region, vintage, body, sweetness, acidity, tannin,
  alcohol_pct, price, description, tasting_notes, flavor_profile, style_tags, food_pairings,
  occasions, image_url, shop_link, source_name, source_kind, source_url, last_scraped_at,
  in_stock, staff_pick
) VALUES
('oh-vintner-cab-2022', 'Vintner Cabernet Sauvignon 2022', 'ONEHOPE Wine', 'red', 'cabernet-sauvignon', 'california', 2022, 'full', 'dry', 'medium', 'high', 14.2, 29.00, 'A plush California Cabernet from ONEHOPE''s Vintner tier with ripe dark fruit and an approachable finish.', 'Black cherry, blackberry, cocoa, vanilla, and soft oak.', '["berry","blackberry","chocolate","vanilla"]', '[]', '["steak","lamb","cheese"]', '["dinner-party","gift"]', NULL, 'https://onehopewine.com/collections/red-wine', 'ONEHOPE Wine', 'official', 'https://onehopewine.com/collections/red-wine', '2026-04-13T00:00:00Z', 1, 1),
('oh-vintner-red-blend-2022', 'Vintner Red Blend 2022', 'ONEHOPE Wine', 'red', 'red-blend', 'california', 2022, 'medium', 'dry', 'medium', 'medium', 13.8, 29.00, 'A fruit-forward California red blend built for easy entertaining and versatile food pairing.', 'Red plum, blackberry, baking spice, and vanilla.', '["berry","cherry","spice","vanilla"]', '[]', '["pasta","pizza","charcuterie"]', '["casual","dinner-party"]', NULL, 'https://onehopewine.com/collections/red-wine', 'ONEHOPE Wine', 'official', 'https://onehopewine.com/collections/red-wine', '2026-04-13T00:00:00Z', 1, 0),
('oh-field-to-table-red-blend-2021', 'Field to Table Red Blend 2021', 'ONEHOPE Wine', 'red', 'red-blend', 'central-coast', 2021, 'medium', 'dry', 'medium', 'medium', 14.0, 38.00, 'ONEHOPE''s best-selling Central Coast red blend made for the table and crowd-pleasing meals.', 'Jammy blackberry, red plum, warm spice, and soft vanilla.', '["blackberry","cherry","spice","vanilla"]', '[]', '["steak","pasta","charcuterie"]', '["dinner-party","casual","gift"]', NULL, 'https://onehopewine.com/collections/best-sellers', 'ONEHOPE Wine', 'official', 'https://onehopewine.com/collections/best-sellers', '2026-04-13T00:00:00Z', 1, 1),
('oh-reserve-paso-cab-2023', 'Reserve Paso Robles Cabernet Sauvignon 2023', 'ONEHOPE Wine', 'red', 'cabernet-sauvignon', 'paso-robles', 2023, 'full', 'dry', 'medium', 'high', 14.5, 48.00, 'A richer reserve-tier Cabernet with Paso Robles depth, oak polish, and steakhouse structure.', 'Cassis, blackberry, cedar, dark chocolate, and baking spice.', '["berry","blackberry","chocolate","pepper","vanilla"]', '[]', '["steak","lamb","cheese"]', '["gift","dinner-party","celebration"]', NULL, 'https://onehopewine.com/pages/corporate-gifts', 'ONEHOPE Wine', 'official', 'https://onehopewine.com/pages/corporate-gifts', '2026-04-13T00:00:00Z', 1, 1),
('oh-vintner-pinot-noir-2020', 'Vintner Pinot Noir 2020', 'ONEHOPE Wine', 'red', 'pinot-noir', 'california', 2020, 'medium', 'dry', 'high', 'low', 13.6, 28.00, 'A silky California Pinot Noir with bright fruit and easy-drinking elegance.', 'Cherry, raspberry, dried rose, and earth.', '["cherry","berry","floral","earthy"]', '[]', '["salmon","poultry","charcuterie"]', '["date-night","casual"]', NULL, 'https://onehopewine.com/collections/red-wine', 'ONEHOPE Wine', 'official', 'https://onehopewine.com/collections/red-wine', '2026-04-13T00:00:00Z', 1, 0),
('oh-reserve-monterey-pinot-noir-2021', 'Reserve Monterey Pinot Noir 2021', 'ONEHOPE Wine', 'red', 'pinot-noir', 'monterey-county', 2021, 'medium', 'dry', 'high', 'low', 13.7, 35.00, 'A reserve Monterey Pinot Noir with more depth, savory lift, and polished texture.', 'Red cherry, cranberry, mushroom, and forest floor.', '["cherry","berry","earthy","herbal"]', '[]', '["salmon","poultry","mushroom"]', '["date-night","dinner-party"]', NULL, 'https://onehopewine.com/collections/red-wine', 'ONEHOPE Wine', 'official', 'https://onehopewine.com/collections/red-wine', '2026-04-13T00:00:00Z', 1, 0),
('oh-vintner-sauvignon-blanc-2023', 'Vintner Sauvignon Blanc 2023', 'ONEHOPE Wine', 'white', 'sauvignon-blanc', 'california', 2023, 'light', 'dry', 'high', 'low', 13.1, 26.00, 'A bright, citrus-driven Sauvignon Blanc with easy California freshness.', 'Lime zest, grapefruit, tropical fruit, and fresh herbs.', '["citrus","grapefruit","tropical","herbal"]', '[]', '["seafood","salad","shellfish"]', '["casual","date-night"]', NULL, 'https://onehopewine.com/', 'ONEHOPE Wine', 'official', 'https://onehopewine.com/', '2026-04-13T00:00:00Z', 1, 1),
('oh-vintner-chardonnay-2023', 'Vintner Chardonnay 2023', 'ONEHOPE Wine', 'white', 'chardonnay', 'california', 2023, 'medium', 'dry', 'medium', 'low', 13.5, 27.00, 'A balanced California Chardonnay with ripe fruit and soft oak influence.', 'Golden apple, peach, lemon cream, and vanilla.', '["peach","citrus","vanilla","caramel"]', '[]', '["poultry","seafood","pasta"]', '["dinner-party","casual"]', NULL, 'https://onehopewine.com/', 'ONEHOPE Wine', 'official', 'https://onehopewine.com/', '2026-04-13T00:00:00Z', 1, 1),
('oh-russian-river-chardonnay-2021', 'Russian River Chardonnay 2021', 'ONEHOPE Wine', 'white', 'chardonnay', 'russian-river-valley', 2021, 'full', 'dry', 'medium', 'low', 14.0, 60.00, 'An exclusive Russian River Chardonnay with richer texture and layered oak spice.', 'White peach, baked apple, lemon curd, and toasted oak.', '["peach","citrus","vanilla","caramel"]', '[]', '["poultry","seafood","pasta","cheese"]', '["gift","dinner-party"]', NULL, 'https://onehopewine.com/pages/holiday-gift-guide', 'ONEHOPE Wine', 'official', 'https://onehopewine.com/pages/holiday-gift-guide', '2026-04-13T00:00:00Z', 1, 0),
('oh-vintner-moscato-2021', 'Vintner Moscato 2021', 'ONEHOPE Wine', 'white', 'moscato', 'california', 2021, 'light', 'sweet', 'medium', 'low', 10.5, 25.00, 'A floral California Moscato with soft sweetness and easy sipping appeal.', 'Peach, apricot, orange blossom, and honey.', '["peach","tropical","floral"]', '["moscato"]', '["dessert","fruit","cheese"]', '["casual","celebration"]', NULL, 'https://onehopewine.com/collections/best-sellers', 'ONEHOPE Wine', 'official', 'https://onehopewine.com/collections/best-sellers', '2026-04-13T00:00:00Z', 1, 0),
('oh-love-language-rose-nv', 'Love Language Rosé NV', 'ONEHOPE Wine', 'rose', 'grenache', 'california', NULL, 'light', 'dry', 'high', 'low', 12.5, 22.00, 'A fresh California rosé with easygoing summer energy and bright fruit.', 'Strawberry, watermelon, citrus peel, and white flowers.', '["berry","citrus","floral"]', '[]', '["charcuterie","salad","seafood"]', '["casual","date-night","celebration"]', NULL, 'https://onehopewine.com/', 'ONEHOPE Wine', 'official', 'https://onehopewine.com/', '2026-04-13T00:00:00Z', 1, 1),
('oh-vintner-sparkling-brut-nv', 'Vintner Sparkling Brut NV', 'ONEHOPE Wine', 'sparkling', 'white-blend', 'california', NULL, 'light', 'dry', 'high', 'low', 11.5, 29.00, 'A crisp California sparkling brut with fine bubbles and broad crowd appeal.', 'Green apple, pear, citrus, and a creamy finish.', '["citrus","green-apple","peach"]', '["brut"]', '["shellfish","cheese","fruit"]', '["celebration","gift","casual"]', NULL, 'https://onehopewine.com/pages/holiday-gift-guide', 'ONEHOPE Wine', 'official', 'https://onehopewine.com/pages/holiday-gift-guide', '2026-04-13T00:00:00Z', 1, 1),
('oh-pink-shimmer-rose-nv', 'Pink Shimmer Sparkling Rosé NV', 'ONEHOPE Wine', 'sparkling', NULL, 'california', NULL, 'light', 'dry', 'high', 'low', 11.5, 49.00, 'ONEHOPE''s Pink Shimmer sparkling rosé built for celebrations, gifting, and statement pours.', 'Pomegranate, pink lady apple, floral notes, and fresh berry lift.', '["berry","citrus","floral"]', '["sparkling-rose","brut"]', '["charcuterie","fruit","dessert"]', '["celebration","gift","date-night"]', NULL, 'https://onehopewine.com/pages/holiday-gift-guide', 'ONEHOPE Wine', 'official', 'https://onehopewine.com/pages/holiday-gift-guide', '2026-04-13T00:00:00Z', 1, 1),
('oh-sparkling-moscato-2021', 'Sparkling Moscato 2021', 'ONEHOPE Wine', 'sparkling', 'moscato', 'california', 2021, 'light', 'sweet', 'medium', 'low', 9.5, 20.00, 'A lightly effervescent sparkling Moscato with fruit-forward sweetness and party-ready energy.', 'Peach, apricot, tropical fruit, and white blossom.', '["peach","tropical","floral"]', '["moscato"]', '["dessert","fruit","cheese"]', '["celebration","casual"]', NULL, 'https://onehopewine.com/pages/holiday-gift-guide', 'ONEHOPE Wine', 'official', 'https://onehopewine.com/pages/holiday-gift-guide', '2026-04-13T00:00:00Z', 1, 0),
('oh-reserve-dessert-wine-nv', 'Reserve Dessert Wine NV', 'ONEHOPE Wine', 'dessert', 'white-blend', 'california', NULL, 'full', 'sweet', 'high', 'low', 14.5, 28.00, 'A rich California dessert wine meant for chocolate and after-dinner pours.', 'Caramel, apricot, candied citrus, and honeyed spice.', '["peach","vanilla","caramel"]', '[]', '["dessert","fruit","cheese"]', '["gift","celebration","dinner-party"]', NULL, 'https://onehopewine.com/collections/red-wine', 'ONEHOPE Wine', 'official', 'https://onehopewine.com/collections/red-wine', '2026-04-13T00:00:00Z', 1, 0);

-- ============================================
-- MERCHANT WINES
-- ============================================

INSERT OR REPLACE INTO wines (
  id, name, brand, wine_type, varietal, region, vintage, body, sweetness, acidity, tannin,
  alcohol_pct, price, description, tasting_notes, flavor_profile, style_tags, food_pairings,
  occasions, image_url, shop_link, source_name, source_kind, source_url, last_scraped_at,
  in_stock, staff_pick
) VALUES
('m-cab-silver-oak', 'Silver Oak Cabernet Sauvignon', 'Silver Oak', 'red', 'cabernet-sauvignon', 'napa-valley', 2019, 'full', 'dry', 'medium', 'high', 14.8, 85.00, 'Iconic Napa Cabernet with deep concentration, velvety tannins, and remarkable aging potential.', 'Blackberry, cassis, dark chocolate, espresso, and cedar. Velvety tannins with an exceptionally long finish.', '["blackberry","cherry","chocolate","coffee","vanilla"]', '[]', '["steak","lamb"]', '["gift","dinner-party"]', NULL, NULL, 'Wine.com', 'merchant', NULL, '2026-04-13T00:00:00Z', 1, 1),
('m-merlot-duckhorn', 'Duckhorn Merlot', 'Duckhorn Vineyards', 'red', 'merlot', 'napa-valley', 2020, 'full', 'dry', 'medium', 'medium', 14.5, 55.00, 'Plush and polished Merlot with layers of dark fruit and supple tannins.', 'Plum, black cherry, mocha, and baking spice. Smooth, round mouthfeel with integrated oak.', '["cherry","plum","chocolate","spice"]', '[]', '["steak","pork","pasta"]', '["dinner-party","casual"]', NULL, NULL, 'Wine.com', 'merchant', NULL, '2026-04-13T00:00:00Z', 1, 0),
('m-pinot-oregon', 'Domaine Drouhin Pinot Noir', 'Domaine Drouhin', 'red', 'pinot-noir', 'willamette-valley', 2020, 'medium', 'dry', 'high', 'low', 13.5, 45.00, 'Oregon Pinot Noir with Burgundian elegance. Bright fruit, earthy complexity, and silky texture.', 'Red cherry, cranberry, mushroom, and dried herbs. Silky texture with a long, savory finish.', '["cherry","berry","earthy","herbal"]', '[]', '["salmon","poultry","mushroom"]', '["date-night","dinner-party"]', NULL, NULL, 'Wine.com', 'merchant', NULL, '2026-04-13T00:00:00Z', 1, 1),
('m-syrah-rhone', 'E. Guigal Côtes du Rhône', 'E. Guigal', 'red', 'syrah', 'rhone-valley', 2021, 'medium', 'dry', 'medium', 'medium', 14.0, 18.00, 'Classic Rhône blend with dark fruit, black pepper, and Mediterranean herbs. Outstanding value.', 'Blackberry, black pepper, lavender, and garrigue herbs. Medium body with a spicy, savory finish.', '["blackberry","pepper","spice","herbal"]', '[]', '["lamb","pork","charcuterie"]', '["casual","cooking"]', NULL, NULL, 'Wine.com', 'merchant', NULL, '2026-04-13T00:00:00Z', 1, 0),
('m-malbec-mendoza', 'Catena Malbec', 'Bodega Catena Zapata', 'red', 'malbec', 'mendoza', 2021, 'full', 'dry', 'medium', 'medium', 14.0, 22.00, 'High-altitude Argentine Malbec with intense dark fruit, violet notes, and smooth tannins.', 'Dark plum, blackberry, violet, cocoa, and a hint of vanilla. Plush tannins with a juicy finish.', '["plum","blackberry","chocolate","floral"]', '[]', '["steak","lamb","pizza"]', '["casual","dinner-party"]', NULL, NULL, 'Wine.com', 'merchant', NULL, '2026-04-13T00:00:00Z', 1, 0),
('m-zinfandel-ridge', 'Ridge Lytton Springs Zinfandel', 'Ridge Vineyards', 'red', 'zinfandel', 'sonoma', 2020, 'full', 'dry', 'medium', 'medium', 14.9, 42.00, 'Bold Sonoma Zinfandel blend with explosive fruit, baking spice, and brambly character.', 'Raspberry, boysenberry, black pepper, clove, and chocolate. Rich and jammy with a long spicy finish.', '["berry","cherry","pepper","spice","chocolate"]', '[]', '["steak","pork","pizza","charcuterie"]', '["casual","dinner-party"]', NULL, NULL, 'Wine.com', 'merchant', NULL, '2026-04-13T00:00:00Z', 1, 0),
('m-red-blend-pedroncelli', 'Pedroncelli Sonoma Classico Red Blend 2023', 'Pedroncelli', 'red', 'red-blend', 'dry-creek-valley', 2023, 'medium', 'dry', 'medium', 'medium', 13.8, 19.97, 'A medium-bodied Sonoma red blend with juicy fruit and warm baking spice.', 'Jammy blackberry, red plum, violet, vanilla, toasted oak, and pepper.', '["blackberry","cherry","spice","vanilla"]', '[]', '["pizza","pasta","charcuterie"]', '["casual","dinner-party"]', NULL, 'https://www.wine.com/product/pedroncelli-sonoma-classico-red-blend-2018/723739', 'Wine.com', 'merchant', 'https://www.wine.com/product/pedroncelli-sonoma-classico-red-blend-2018/723739', '2026-04-13T00:00:00Z', 1, 0),
('m-sauv-blanc-cloudy-bay', 'Cloudy Bay Sauvignon Blanc', 'Cloudy Bay', 'white', 'sauvignon-blanc', 'marlborough', 2023, 'light', 'dry', 'high', 'low', 13.0, 26.00, 'Benchmark Marlborough Sauvignon Blanc. Explosive citrus and tropical fruit with vibrant acidity.', 'Passionfruit, grapefruit, lime zest, and fresh-cut grass. Bright acidity with a clean, lingering finish.', '["citrus","grapefruit","tropical"]', '[]', '["seafood","salad","shellfish"]', '["casual","date-night"]', NULL, NULL, 'Wine.com', 'merchant', NULL, '2026-04-13T00:00:00Z', 1, 1),
('m-riesling-dr-loosen', 'Dr. Loosen Blue Slate Riesling Kabinett', 'Dr. Loosen', 'white', 'riesling', 'mosel', 2022, 'light', 'off-dry', 'high', 'low', 8.5, 18.00, 'Delicate Mosel Riesling with floral aromatics, green apple, and electric acidity.', 'Green apple, white peach, honeysuckle, and wet slate. Off-dry with a long mineral finish.', '["citrus","green-apple","floral","mineral"]', '[]', '["seafood","poultry","vegetables"]', '["casual","date-night"]', NULL, NULL, 'Wine.com', 'merchant', NULL, '2026-04-13T00:00:00Z', 1, 0),
('m-pinot-grigio-santa-margherita', 'Santa Margherita Pinot Grigio', 'Santa Margherita', 'white', 'pinot-grigio', 'veneto', 2023, 'light', 'dry', 'medium', 'low', 12.5, 22.00, 'Clean and crisp Italian Pinot Grigio with broad food-pairing appeal.', 'Golden Delicious apple, citrus, and white flowers with a long layered finish.', '["citrus","green-apple","floral"]', '[]', '["seafood","salad","pasta"]', '["casual"]', NULL, 'https://www.wine.com/product/santa-margherita-pinot-grigio-375ml-half-bottle-2019/605422', 'Wine.com', 'merchant', 'https://www.wine.com/product/santa-margherita-pinot-grigio-375ml-half-bottle-2019/605422', '2026-04-13T00:00:00Z', 1, 0),
('m-white-blend-conundrum', 'Conundrum White Blend 2023', 'Conundrum', 'white', 'white-blend', 'california', 2023, 'medium', 'off-dry', 'medium', 'low', 13.5, 15.97, 'A full-flavored California white blend with exotic fruit and broad crowd appeal.', 'Tropical fruit, peach, citrus, and floral spice.', '["tropical","peach","citrus","floral"]', '[]', '["poultry","seafood","salad"]', '["casual","dinner-party"]', NULL, 'https://www.wine.com/product/conundrum-white-blend-2010/111472', 'Wine.com', 'merchant', 'https://www.wine.com/product/conundrum-white-blend-2010/111472', '2026-04-13T00:00:00Z', 1, 0),
('m-rose-whispering-angel', 'Whispering Angel Rosé', 'Caves d''Esclans', 'rose', 'grenache', 'provence', 2023, 'light', 'dry', 'high', 'low', 13.0, 24.00, 'The benchmark Provence rosé. Pale pink, bone dry, and beautifully refreshing.', 'Strawberry, white peach, citrus blossom, and sea salt. Bone dry with a crisp mineral finish.', '["berry","citrus","floral","mineral"]', '[]', '["seafood","salad","shellfish","charcuterie"]', '["casual","date-night","celebration"]', NULL, NULL, 'Wine.com', 'merchant', NULL, '2026-04-13T00:00:00Z', 1, 1),
('m-champagne-veuve', 'Veuve Clicquot Yellow Label Brut', 'Veuve Clicquot', 'sparkling', 'champagne-blend', 'champagne', NULL, 'medium', 'dry', 'high', 'low', 12.0, 55.00, 'A classic Champagne with structure, brioche depth, and fine bubbles.', 'Yellow apple, lemon, brioche, vanilla, and almond.', '["citrus","green-apple","vanilla","caramel"]', '["champagne","brut"]', '["shellfish","cheese","fruit"]', '["celebration","gift","dinner-party"]', NULL, 'https://www.wine.com/product/veuve-clicquot-yellow-label-brut-15-liter-magnum/15511', 'Wine.com', 'merchant', 'https://www.wine.com/product/veuve-clicquot-yellow-label-brut-15-liter-magnum/15511', '2026-04-13T00:00:00Z', 1, 1),
('m-prosecco-la-marca', 'La Marca Prosecco', 'La Marca', 'sparkling', 'prosecco-blend', 'veneto', NULL, 'light', 'off-dry', 'medium', 'low', 11.2, 18.97, 'A bright, approachable Prosecco with lively bubbles and brunch-ready freshness.', 'Citrus, green apple, ripe lemon, peach, and minerality.', '["citrus","green-apple","peach","floral"]', '["prosecco"]', '["fruit","shellfish","salad"]', '["casual","celebration","brunch"]', NULL, 'https://www.wine.com/product/la-marca-prosecco/24828?iid=brunchcocktails', 'Wine.com', 'merchant', 'https://www.wine.com/product/la-marca-prosecco/24828?iid=brunchcocktails', '2026-04-13T00:00:00Z', 1, 0),
('m-cava-codorniu', 'Codorniu Cava Brut', 'Codorniu', 'sparkling', 'white-blend', 'cava', NULL, 'light', 'dry', 'high', 'low', 11.5, 17.99, 'A bright Spanish Cava with crisp citrus and savory mineral lift.', 'Lemon peel, green apple, toasted bread, and minerality.', '["citrus","green-apple","mineral"]', '["cava","brut"]', '["shellfish","cheese","charcuterie"]', '["celebration","casual"]', NULL, NULL, 'Wine.com', 'merchant', NULL, '2026-04-13T00:00:00Z', 1, 0),
('m-cremant-domaine-sarrazin', 'Domaine Sarrazin Crémant de Bourgogne Brut', 'Domaine Sarrazin', 'sparkling', 'white-blend', 'burgundy', NULL, 'light', 'dry', 'high', 'low', 12.0, 24.99, 'A traditional-method Crémant with orchard fruit, brisk acidity, and fine mousse.', 'Apple, pear, lemon zest, and brioche.', '["citrus","green-apple","vanilla"]', '["cremant","brut"]', '["shellfish","cheese","fruit"]', '["celebration","gift"]', NULL, NULL, 'Wine.com', 'merchant', NULL, '2026-04-13T00:00:00Z', 1, 0),
('m-blanc-de-blancs-le-cardinale', 'Le Cardinale Blanc de Blancs', 'Le Cardinale', 'sparkling', 'chardonnay', 'alsace', NULL, 'light', 'dry', 'high', 'low', 10.5, 9.99, 'An easy-drinking Blanc de Blancs with bright lemon and clean balance.', 'Lemon, honey, apple, and a clean crisp finish.', '["citrus","green-apple","vanilla"]', '["blanc-de-blancs","brut"]', '["shellfish","cheese","fruit"]', '["casual","celebration"]', NULL, 'https://www.wine.com/product/le-cardinale-blanc-de-blancs/154752', 'Wine.com', 'merchant', 'https://www.wine.com/product/le-cardinale-blanc-de-blancs/154752', '2026-04-13T00:00:00Z', 1, 0),
('m-sparkling-rose-gruet', 'Gruet Brut Rosé', 'Gruet', 'sparkling', NULL, 'new-mexico', NULL, 'light', 'dry', 'high', 'low', 12.0, 19.99, 'A bright domestic sparkling rosé with vivid berry fruit and brisk acidity.', 'Wild strawberry, raspberry, citrus peel, and flowers.', '["berry","citrus","floral"]', '["sparkling-rose","brut"]', '["charcuterie","fruit","dessert"]', '["celebration","date-night"]', NULL, NULL, 'Wine.com', 'merchant', NULL, '2026-04-13T00:00:00Z', 1, 0),
('m-dessert-yquem', 'Château d''Yquem Sauternes', 'Château d''Yquem', 'dessert', 'white-blend', 'bordeaux', 2017, 'full', 'sweet', 'high', 'low', 14.0, 350.00, 'An iconic Sauternes with remarkable richness, length, and age-worthy precision.', 'Honey, saffron, apricot, candied citrus peel, and crème brûlée.', '["tropical","peach","vanilla","caramel"]', '[]', '["dessert","cheese","fruit"]', '["gift","celebration","dinner-party"]', NULL, NULL, 'Wine.com', 'merchant', NULL, '2026-04-13T00:00:00Z', 1, 1),
('m-dessert-vietti-moscato', 'Vietti Moscato d''Asti', 'Vietti', 'dessert', 'moscato', 'piedmont', 2023, 'light', 'sweet', 'medium', 'low', 5.5, 18.00, 'A gently sparkling Moscato d''Asti with low alcohol and lifted orchard fruit.', 'Peach, apricot, orange blossom, and honey.', '["peach","tropical","floral"]', '["moscato"]', '["dessert","fruit"]', '["casual","celebration"]', NULL, NULL, 'Wine.com', 'merchant', NULL, '2026-04-13T00:00:00Z', 1, 0);

-- ============================================
-- OFFICIAL MERCHANT EXPANSION
-- ============================================

INSERT OR REPLACE INTO wines (
  id, name, brand, wine_type, varietal, region, vintage, body, sweetness, acidity, tannin,
  alcohol_pct, price, description, tasting_notes, flavor_profile, style_tags, food_pairings,
  occasions, image_url, shop_link, source_name, source_kind, source_url, last_scraped_at,
  in_stock, staff_pick
) VALUES
('m-official-duckhorn-cab-2022', '2022 Duckhorn Vineyards Napa Valley Cabernet Sauvignon', 'Duckhorn Vineyards', 'red', 'cabernet-sauvignon', 'napa-valley', 2022, 'full', 'dry', 'medium', 'high', 14.5, 65.00, 'An official Duckhorn Napa Valley Cabernet sourced from the winery''s current-release product page.', 'Dark red berries, cardamom, fig jam, boysenberry pie, and dusty tannins.', '["berry","blackberry","spice","vanilla"]', '[]', '["steak","lamb","cheese"]', '["gift","dinner-party"]', 'https://www.duckhornwineshop.com/assets/images/products/pictures/the-duckhorn-portfolio-2022-duckhorn-vineyards-napa-valley-cabernet-sauvignon.jpg', 'https://www.duckhorn.com/product/2022-duckhorn-vineyards-napa-valley-cabernet-sauvignon', 'Duckhorn Vineyards', 'official', 'https://www.duckhorn.com/product/2022-duckhorn-vineyards-napa-valley-cabernet-sauvignon', '2026-04-13T00:00:00Z', 1, 1),
('m-official-duckhorn-cab-franc-2012', '2012 Duckhorn Vineyards Napa Valley Cabernet Franc', 'Duckhorn Vineyards', 'red', 'cabernet-franc', 'napa-valley', 2012, 'full', 'dry', 'medium', 'medium', 14.5, 76.00, 'A library-style official Duckhorn Cabernet Franc that broadens merchant coverage for Cabernet Franc drinkers.', 'Blackberry, cassis, violet, pencil shavings, tobacco leaf, and savory herbs.', '["blackberry","berry","floral","herbal"]', '[]', '["steak","lamb","charcuterie"]', '["gift","dinner-party"]', 'https://www.duckhornwineshop.com/assets/images/products/pictures/2012-Duckhorn-Napa-Valley-Cab-Franc.jpg', 'https://www.duckhorn.com/product/2012-Duckhorn-Vineyards-Napa-Valley-Cabernet-Franc', 'Duckhorn Vineyards', 'official', 'https://www.duckhorn.com/product/2012-Duckhorn-Vineyards-Napa-Valley-Cabernet-Franc', '2026-04-13T00:00:00Z', 1, 0),
('m-official-goldeneye-pinot-2017', '2017 Goldeneye Ten Degrees Anderson Valley Pinot Noir', 'Goldeneye Winery', 'red', 'pinot-noir', 'anderson-valley', 2017, 'medium', 'dry', 'high', 'low', 14.2, 185.00, 'An official Goldeneye Pinot Noir from the Duckhorn collection with more luxury-tier Pinot coverage in merchant mode.', 'Blueberry, blackberry, redwood forest, moist earth, and spice.', '["berry","blackberry","earthy","spice"]', '[]', '["duck","salmon","mushroom"]', '["gift","dinner-party"]', 'https://www.duckhornwineshop.com/assets/images/products/pictures/2017-goldeneye-av-ten-degrees-pinot-noir.jpg', 'https://www.goldeneyewinery.com/product/2017-goldeneye-ten-degrees-anderson-valley-pinot-noir', 'Goldeneye Winery', 'official', 'https://www.goldeneyewinery.com/product/2017-goldeneye-ten-degrees-anderson-valley-pinot-noir', '2026-04-13T00:00:00Z', 1, 0),
('m-official-paraduxx-red-2019', '2019 Paraduxx Proprietary Napa Valley Red Wine', 'Paraduxx', 'red', 'red-blend', 'napa-valley', 2019, 'full', 'dry', 'medium', 'medium', 14.5, 56.00, 'An official Paraduxx Napa Valley red blend from the Duckhorn family portfolio.', 'Blackberry, plum, cocoa, spice, and soft elegant tannins.', '["blackberry","cherry","pepper","vanilla"]', '[]', '["steak","pork","charcuterie"]', '["dinner-party","gift"]', 'https://www.duckhornwineshop.com/assets/images/products/pictures/the-duckhorn-portfolio-2019-paraduxx-proprietary-napa-valley-red-wine.jpg', 'https://www.paraduxx.com/product/2019-paraduxx-proprietary-napa-valley-red-wine', 'Paraduxx', 'official', 'https://www.paraduxx.com/product/2019-paraduxx-proprietary-napa-valley-red-wine', '2026-04-13T00:00:00Z', 1, 0),
('m-official-decoy-sauvignon-2023', '2023 Decoy California Sauvignon Blanc', 'Decoy', 'white', 'sauvignon-blanc', 'california', 2023, 'light', 'dry', 'high', 'low', 13.5, 20.00, 'An official Decoy Sauvignon Blanc that expands merchant white coverage with another clean, citrus-driven option.', 'Citrus, passion fruit, green apple, and fresh herbs.', '["citrus","green-apple","tropical","herbal"]', '[]', '["seafood","salad","shellfish"]', '["casual","date-night"]', 'https://www.duckhornwineshop.com/assets/images/products/pictures/the-duckhorn-portfolio-2023-decoy-california-sauvignon-blanc.jpg', 'https://www.decoywines.com/product/2023-decoy-california-sauvignon-blanc', 'Decoy', 'official', 'https://www.decoywines.com/product/2023-decoy-california-sauvignon-blanc', '2026-04-13T00:00:00Z', 1, 0),
('m-official-calera-chardonnay-2016', '2016 Calera Central Coast Chardonnay', 'Calera Wine Company', 'white', 'chardonnay', 'central-coast', 2016, 'medium', 'dry', 'medium', 'low', 14.2, 28.00, 'An official Calera Chardonnay that strengthens merchant Chardonnay coverage from another premium producer.', 'Jasmine, vanilla bean, passion fruit, green apple, grapefruit, and subtle oak.', '["green-apple","citrus","tropical","vanilla"]', '[]', '["poultry","seafood","pasta"]', '["dinner-party","casual"]', 'https://www.duckhornwineshop.com/assets/images/products/pictures/2016-calera-central-coast-chardonnay.jpg', 'https://www.calerawine.com/product/2016-central-coast-chardonnay', 'Calera Wine Company', 'official', 'https://www.calerawine.com/product/2016-central-coast-chardonnay', '2026-04-13T00:00:00Z', 1, 0),
('m-official-mersoleil-silver-2023', '2023 Mer Soleil SILVER Chardonnay Monterey County', 'Mer Soleil', 'white', 'chardonnay', 'monterey-county', 2023, 'medium', 'dry', 'high', 'low', 13.8, 18.00, 'An official Wagner family Chardonnay from the Mer Soleil lineup with stainless-steel freshness and coastal minerality.', 'Citrus, wet granite, lively minerality, and vibrant acidity.', '["citrus","mineral","green-apple"]', '[]', '["seafood","salad","shellfish"]', '["casual","dinner-party"]', NULL, 'https://www.wagnerfamilyofwine.com/wine-shop/mer-soleil/', 'Mer Soleil', 'official', 'https://www.wagnerfamilyofwine.com/wine-shop/mer-soleil/', '2026-04-13T00:00:00Z', 1, 0),
('m-official-mersoleil-reserve-2023', '2023 Mer Soleil Reserve Chardonnay Santa Lucia Highlands', 'Mer Soleil', 'white', 'chardonnay', 'santa-lucia-highlands', 2023, 'full', 'dry', 'medium', 'low', 14.2, 24.00, 'An official Wagner family reserve Chardonnay with richer texture and more classic Monterey Coast weight.', 'Custard, toasted almonds, lemon, lime, and rich fruit.', '["peach","citrus","vanilla"]', '[]', '["seafood","poultry","pasta"]', '["gift","dinner-party"]', NULL, 'https://www.wagnerfamilyofwine.com/wine-shop/mer-soleil/', 'Mer Soleil', 'official', 'https://www.wagnerfamilyofwine.com/wine-shop/mer-soleil/', '2026-04-13T00:00:00Z', 1, 0);
